<?php

//配置文件
return [
    'url_common_param'       => true,
    'url_html_suffix'        => '',
    'controller_auto_search' => true,

    'menus'=>[
        'About Us',
        'Student Guides and Resources',
        'Updates and Newsletters',
        'Entry Requirements',
        'Key Dates',
        'Upcoming Events',
        'Scholarships',
        'Agent Manual',
        'Meet our Team',
        'Order Student Guides',
        'Quick Links'
    ],

    'trans'=>[
        'Digital Agent Hub',
        'Login to My Account',
        'E-mail',
        'Password',
        'Login',
        'Forgot password',
        'Remember me',
        'Create account',
        'About Us',
        'Student Guides and Resources',
        'Student Guides',
        'Program Flyers',
        'Pull Up Banners',
        'Templates',
        'Brand Guidelines',
        'System User Guides',
        'Video and Webinar Library',
        'Image Library',
        'FAQs',
        'Updates and Newsletters',
        'Entry Requirements',
        'Key Dates',
        'Upcoming Events',
        'Scholarships',
        'Agent Manual',
        'Meet our Team',
        'Order Student Guides',
        'Quick Links',
        'Contact us',
        'Log out',
        'Change my Password',
        'Current password',
        'New password',
        'Confirm password',
        'Submit',
        'My Account',
        'How to Apply',
        'My personal details',
        'My downloads',
        'My favourites',
        'Full name',
        'Email address',
        'Country',
        'Company',
        'Edit my details',
        'Change password',
        'Send',
        'Please enter the email address you used to sign up so we can send you an email with a link to reset your password.',
        'New password',
        'Confirm password',
        'My downloaded images',
        'Welcome',
        'Full name',
        'Password',
        'Sign up',
        'UNSW Sydney FAQs',
        'UNSW Global FAQs',
        'Please login first',
        'Please enter email' ,
        'Email is invalid' ,
        'Please enter password',
        'This email does not exist',
        'Please enter the correct password',
        'Login successful' ,
        'Please enter the full name',
        'Please enter confirmed password',
        'Registration completed',
        'Registration failed',
        'Login successful',
        'Sent successfully',
        'Password and confirmed password not matched' ,
        'Password is reset' ,
        'Operation completed',
        'Please enter country',
        'Please enter company',
        'The Email has been registered',
        'Logout successfully',
        'Please enter search keywords',
        'End',
        'END',
        'Confirm',
        'Cancel',
        'Please choose team'
    ],
    'aws'=>[
        'bucket'=>'unsw-militech',
        'domain'=>'https://dn7e6763drusk.cloudfront.net/',
        'region'=>'ap-southeast-2'
    ]
];
